### ISSUE TITLE
ACMEv2 — Call for alpha testing

### ISSUE THREAD

**Issue by hlandau** [hlandau/acmetool#305]
[ACMEv2 support](https://github.com/hlandau/acme/issues/294) is being developed in the `acmev2` branch. Consider that:
- It is *very alpha*.
- Wildcard certificates are supported. e.g. `acmetool want '*.example.com'`. Since Let's Encrypt requires the use of the DNS challenge for wildcard certificates, having a DNS challenge hook script setup is mandatory for this.
- ACMEv1 support is removed, since all available endpoints (Let's Encrypt) now support ACMEv2.
- The old Let's Encrypt production directory URL will be automatically converted to the correct ACMEv2 URL.
- That said, full support for seamless in-place upgrades from acmetool v0.0.x **is not yet complete.** Use a fresh `/var/lib/acme`, or at the very least make backups of your existing one. Otherwise, expect breakage.
- The `acmeapi` package, which was originally in the same repository, has been factored out to a separate repository, https://github.com/hlandau/acmeapi. This package targets ACMEv2 only.
- https://github.com/hlandau/acme will be renamed to `https://github.com/hlandau/acmetool` once v0.2.1 is released. The old URL will redirect. Also, `go install https://github.com/hlandau/acmetool` will be the preferred installation method, and `go install https://github.com/hlandau/acme[tool]/cmd/acmetool` will be deprecated, but still work.
- Since it's an alpha, don't use it for critical purposes and don't expect it to work well.
- Bug reports for this alpha are welcome. Please create an issue with title beginning `acmev2: `.
- Expect further significant changes.

Once ACMEv2 support is fully done and tested, v0.2.1 will be released, which will be the first tagged release to support ACMEv2.

**Comment by k3a** [comment]
Confirming `acmev2` branch works, together with https://github.com/hlandau/acme/blob/master/_doc/dns.hook I was able to get a wildcard certificate. 

There was just this easy-to-fix issue:
```gopkg.in/hlandau/easyconfig.v1/adaptflag/adaptflag.go:227:17: cannot use r (type rune) as type byte in argument to fl.Short```

I backed up `/var/lib/acme/` before doing that. And I had to manually update `/var/lib/acme/conf/target` to `acme-v02` API URL. I am yet to see if renewing pre-2.0 certificates will work with this alpha branch but it looks promising.

For the wildcard certificate with DNS hook, one needs to host their own Bind nameservers. Then generate TSIG shared secret using e.g. `dnssec-keygen -a hmac-sha256 -b 256 -n HOST acme-update.key` and add the key to allow-update in `named.conf` like:
```
# allowing local acme updates
key acme_updates {
    algorithm hmac-sha256;
    secret "base64 of shared secret key";
};

...

    allow-update {
        /* allow acme update key */
        key acme_updates.; 
    };
``` 

then add the shared secret as TKIP_KEY_NAME and TKIP_KEY to /etc/conf.d/acme-dns like
```
TKIP_KEY_NAME="hmac-sha256:acme_updates"
TKIP_KEY="base64 of shared secret key"
```

Variables should probably be called TSIG_* instead of TKIP_* as TKIP is Wifi-related Temporal Key Integrity Protocol and Bind uses TSIG - see https://www.cyberciti.biz/faq/unix-linux-bind-named-configuring-tsig/ for more info on how it works. It is also used for secure transfer of updates to DNS slaves.

DON'T FORGET TO PREVENT /etc/conf.d/acme-dns AND named.conf TO BE WORLD-READABLE. Otherwise anyone with access to these files would read the shared secret and be able to issue DNS updates.

**Comment by hlandau** [comment]
@k3a Thanks for trying it out.

It's supposed to replace known ACMEv1 endpoint URLs with the v2 endpoints automatically; do you know what URL you had configured previously so I can check why it wasn't recognised?

As for the TKIP thing, huh, brainfart. I'll fix it, while supporting the old names for backwards compatibility.

**Comment by k3a** [comment]
Yes, I have the whole /var/lib/acme backed up just in case.

My conf/target content was
```
request:
  provider: https://acme-v01.api.letsencrypt.org/directory
```

Re TKIP that happens ;) thanks for keeping backward compatibility in mind.

**Comment by drlogout** [comment]
Hi,

I'm a bit confused. Does the newest version v0.0.67 support the acme-v02.api? I can't find anything in the documentation and acme-v01 support stops on February 13th, 2019.

And do I have to change something else then the provider in `conf/target`?

Cheers
chris

**Comment by cpu** [comment]
> acme-v01 support stops on February 13th, 2019.

Hi @drlogout - I think you've confused the initial deprecation date for the TLS-SNI-01 challenge type with the ACME v1 API. They are separate things and ACME v1 will continue to work after Feb 13th. There is no currently announced deprecation date for that API version.

**Comment by drlogout** [comment]
Ok, yes indeed I did. Thanks!

**Comment by berolinux** [comment]
I've updated my installations - working well here. Even renewing certificates from an existing 0.0.67 installation worked well. Would be good to have some documentation on wildcard certificates though, it's not obvious how to set up a proper DNS challenge hook.

**Comment by afreudenreich** [comment]
I have requested certificates (with several SANs on one cert) successfully using the proxy challenge method. Looking good so far.

**Comment by hlandau** [comment]
Moving to beta, see https://github.com/hlandau/acmetool/issues/322.
