### ISSUE TITLE
Self-signed certificate

### ISSUE THREAD

**Issue by 89z** [hlandau/acmetool#345]
Is it possible to create a self-signed certificate using acmetool? I just want something simple for local HTTPS testing.

**Comment by mnalis** [comment]
Sure it is possible, but why on Earth would you want that?! The **whole point** of acmetool is to use ACME protocol to sign your certificate with **trusted CA**. 

If you want to create self-signed cert, just use `openssl` or some other tool [to do it](https://duckduckgo.com/?q=create+self-signed+certificate), or use already created ones (like for example `/etc/ssl/certs/ssl-cert-snakeoil.pem` on some GNU/Linux systems).

(and in order to do it with acmetool, you would first need to setup your own CA with your own ACME server endpoint and point acmetool to it, which is about the most complex possible way imaginable to create self signed certificate).

**Comment by 89z** [comment]
I just want to inspect an HTTPS request coming from my computer, using my computer. I think self-signed certificate is the "right way" to do that, but I dont know. I just need to capture the TLS Client Hello, so whatever the easiest way to do that is.

**Comment by mnalis** [comment]
That seems to have nothing to do with self-signed certificate, much less with acmetool.

Also, [TLS Client Hello](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake) message is part of your normal capture log. There is nothing extra you need to "do" to have it. Whether it contains data you are interested in, or not, is a different story. (and the answer is probably not, and what you want is more likely [MiTM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)).

I'd suggest detailing what exactly you **_actually want to accomplish_** (instead of asking for _"what you **think** you need in order to accomplish that"_;  in order to avoid [XY problem](https://en.wikipedia.org/wiki/XY_problem)) somewhere where such messages are on-topic, like (for example) https://security.stackexchange.com/

**Comment by 89z** [comment]
I have blocked @mnalis, as he seems to be distracting from my goal of getting an answer, rather than helping. Also I am keenly aware of the XY problem, I literally wrote the answer for it:

https://meta.stackexchange.com/a/233676

**Comment by 89z** [comment]
Looks like Go includes a program for this already:

https://github.com/golang/go/blob/go1.17.4/src/crypto/tls/generate_cert.go
